### ISSUE TITLE
HG während Ingame-State nicht über's GUI joinbar

### ISSUE THREAD

**Issue by Wxffel** [HGLabor/HardcoreGames#13]
Über das GUI, welches sich öffnet wenn man in der Lobby den Diamanten rechtsklickt, kann man als lebender Spieler nicht rejoinen, wenn sich der HG-Server im Ingame-State befindet (was normalerweise möglich sein sollte und auch per Command geht).

**Comment by copyandexecute** [comment]
BestAuto wird sich darum kümmern
