### ISSUE TITLE
Netherite

### ISSUE THREAD

**Issue by Syriuus** [HGLabor/HardcoreGames#18]
Die Netherite Rüstung im Feast finde ich momentan zu stark (unabhängig von durability das ist was anders)
Die Knockbackresistance die die Rüstung gibt ist mit dem 1.8 Knockback zu stark

Vorschlag: Knockbackresistance entfernen oder Netherite Rüstung entfernen

**Comment by copyandexecute** [comment]
Habe die Wahrscheinlichkeit von Netherriterüstung verringert da ich die trotzdem noch im Spiel haben möchte so als gamechanger
