### ISSUE TITLE
Feast lokalisation

### ISSUE THREAD

**Issue by Wxffel** [HGLabor/HardcoreGames#24]
Um es vielen Spieler einfacher zu machen, schlage ich die Rückkehr des ehemaligen "/feast"-Commands nun auf GitHub vor!

Zuzätzlich möchte ich hier auch nochmal folgendes vorschlagen: Eine Partikelspur zum Feast.
Partikel, welche einem den Weg zum Feast zeigen, kann man natürlich vielseitig umsetzen - das lasse ich offen (bis ich mich dann beschwere lol). Wichtig ist mir aber, dass man diese an- und ausschalten kann.

Beide Funktionen sind natürlich auch für FFA gut, nur eben nicht so dringend.

**Comment by copyandexecute** [comment]
please close this ticket if the issue has been fixed.
