### ISSUE TITLE
HG Update - Suggestion 

### ISSUE THREAD

**Issue by HitzlikeaBanana** [HGLabor/HardcoreGames#35]
Liste hier ein paar Sachen auf die meiner Meinung nach verändert werden müssten, um HG wieder ansprechend zu machen. (Added gerne eure Ideen)

**-** Stats adden (War schon im Gespräch. Gründe: Den Sinn in Hg zu gewinnen fördern, mehr Tryhards = Mehr user i guess)

**-** Naturkatastrophen adden (Dieses mal aber angepasst, also nicht zu stark nicht zu schwach + interaktionen mit Kits die ich gleich erwähne. Gründe: Ka wäre einfach cool alte Sachen verbessert wieder hinzuzufügen)  (Sie werden alle 10 Min Random eintretet und halten 3 Min )

**-** Naturkatastrophen + Kits
Gewitter: Effekt: Es Regnet, Blitze schlagen vermehrt ein - Thor`s Cooldown wird um -50% verringert. Der Einschlag von Thor macht mehr Schaden, mehr Blöcke kaputt, und mehr Feuer.

Orkan/Sandsturm: Effekt: Passende Partikel fliegen herum. Man wird zurück gestoßen (Wie damals) aber man kann sich trotzdem bewegen (natürlich langsamer) man bekommt außerdem in regelmäßigen Abständen ein halbes Herz Schaden. - Grandpa`s Knockbackstick bekommt in der Zeit Knockback 5 statt 2.

Zombieapokalypse : Effekt: Es wird Nacht. Zombies Spawnen vermehrt. - Cannibal verteilt einen noch stärkeren Hunger Effekt. - Wenn man die Zombies mit Manipulation manipuliert haben diese automatisch Regeneration 1 für 30 sekunden. 

(Schwacher Name ik) Poisenrain: Effekt: Lässt es Regnen. Wenn man den Regen berührt bekommt man Poisen 1 durchgehend. - Kit Smogmog ist nicht davon betroffen sonder bekommt sogar Speed 1 und Regeneration 1. - Viper ist ebenfalls nicht davon betroffen und hat jetzt eine 66% Chance zu vergiften.

- Komplett neues Kit: Wetterfrosch Effekt: Bekommt bei JEDER ART VON REGEN (Auch Poisenrain) Jump Boost 2 so wie Regeneration 2. Die effekte Sorgen dafür das man als Wetterfrosch schlecht leute verfolgen kann weshalb die gegner sich aussuchen können ob sie ihn während einer Naturkatastrophe fighten wollen. Außerdem wird er beim Orkan/Sandsturm nicht zurück gedrängt und bekommt keinen Schaden dadurch. Zombies aus der Zombieapokalypse greifen ihn nicht an AUßER sie worden von Kit Manipulation Manipuliert. (Für leute die 0 BOCK auf Nachteile bei Naturkatastrophen haben. Keep in mind die sind ja nicht durchgängig da, außerdem hat es ohne Naturkatastrophen keinen weitern Nutzen daher würde ich es balanced finden)

Vorschlag von Move: Wie damals eig geplant Himmel und Hölle in Hg bringen.
Die Grund Idee war es glaube ich das man ab einer bestimmten Höhe in diese genannte Welt kommt. Da könnte man dann noch andere Kits adden die damit zusammenhängen.

Ist viel zu lesen ik. Und noch viel mehr Aufwand das zu Coden aber waren mal so Ideen die ich mega feiern würde (btw add Kit Redstoner pls :))

**Comment by copyandexecute** [comment]
bitte einzelne posts daraus machen
