### ISSUE TITLE
Feast spawnt über Höhe 128

### ISSUE THREAD

**Issue by Mikasaaaaa** [HGLabor/HardcoreGames#45]
Das Feast kann über Höhe 128 spawnen. Dann können keine Kisten geöffnet/abgebaut werden.

![2021-04-12_19 34 22](https://user-images.githubusercontent.com/74839248/114437807-4d250100-9bc7-11eb-85d2-095969087100.png)

**Comment by r0yzer** [comment]
ist bis jetzt noch nicht passiert also weiss nciht
