### ISSUE TITLE
Gravedigger

### ISSUE THREAD

**Issue by Wxmble** [HGLabor/HardcoreGames#47]
Add Gravedigger :(

**Comment by Hotkeyyy** [comment]
mach issue bei der kitapi

**Comment by realjarek** [comment]
das ganze wär aber vllt als sidekit oder als teil eines anderen kits sinnvoller. Aber dieser Issue kann in jedem Fall geclosed werden

**Comment by Wxmble** [comment]
Gravedigger "Teil eines anderen Kits" oder "Sidekit"? 
Wtf?
