### ISSUE TITLE
viereck feast???

### ISSUE THREAD

**Issue by zImFloydy** [HGLabor/HardcoreGames#50]
![Screenshot (169)](https://user-images.githubusercontent.com/82404889/114763669-5a76f280-9d63-11eb-90fb-038fa1fd40d4.png)
![Screenshot (171)](https://user-images.githubusercontent.com/82404889/114763999-ba6d9900-9d63-11eb-81d8-9e25b4d507ad.png)

**Comment by soho030** [comment]
awe :omegalul:

**Comment by helqless** [comment]
das ist doch kein viereck das ist ein Würfl 🤦‍♂️

**Comment by r0yzer** [comment]
hatte ich jetzt seit dem nicht mehr reopen wenn das nochmal ist ok
