### ISSUE TITLE
Jungle zu Op

### ISSUE THREAD

**Issue by realjarek** [HGLabor/HardcoreGames#51]
Ich finde, dass es sehr unbalanced ist dass man im jungle so viele kakaobohnen bekommt. Wenn man nicht im Jungle war hat man einen enormen Recraftnachteil gegenüber allen spielern die nicht im Jungel waren.
Ich bin auch der Meinung, dass das hier auf HgLabor extremer ist als auf anderen servern da es viel mehr Kakaobohnen pro Junglebaum gibt. Wie wäre es wenn jemand mal eine Abstimmung dazu macht ob die Bohnenanzahl pro Baum niedriger geschraubt werden soll?

Danke

Jarek

**Comment by copyandexecute** [comment]
neue biome sind im anmarsch aber beschwerden diesgezüglich direkt an @Wxmble

**Comment by Wurliiii** [comment]
Lol
