### ISSUE TITLE
Edit boarder for upcoming events

### ISSUE THREAD

**Issue by HitzlikeaBanana** [HGLabor/HardcoreGames#59]
Moin, da es ja beim letzten Event Probleme mit der Border gab und einige sich beschwert haben, haben Mikasa Unknown und ich überlegt was man da machen kann.

Der beste Vorschlag war bisher die Border wie in Endergames zu machen. Also das sie einen weg boosted wenn man zu nah kommt. Diese “endergames border” könnte man ja immer etwas vor der richtigen Border plazieren (gleich schnell shrinken lassen) damit Kits wie Blink oder Ninja etc. nicht außerhalb der Border gelangen.

Außerdem hat der Shrink Command von der Border letztes mal etwas gebuggt.... (not sure but) ich meine die Border hat sich sofort verkleinert anstatt langsam kleiner zu werden. (Wär gut wenn Unknown/Mikasa dazu noch was sagt also hier kommentiert).

**Comment by r0yzer** [comment]
gibt ja jetzt pit ;)
