### ISSUE TITLE
Gulag in HG

### ISSUE THREAD

**Issue by copyandexecute** [HGLabor/HardcoreGames#61]
**Was?**

Gulag aus dem Spiel Warzone kopieren

**Funktion?**

Man kann bis zu einer gewissen Zeit (Abhängig von Spielerzahl, Event, Feast...) **1x** (Setting) nach seinem Tod im Gulag respawnen. Dort muss man gegen einen anderen verstorbenen Spieler kämpfen und der Gewinner darf wieder ins Spiel teleportiert werden (Am besten mit Glideeffekt spawnen lassen + bisschen Standard Equipment)

**Gulag im Detail**

Basically Gulag aus Warzone kopieren aber anstatt einem Pistol-Fight wird es bei uns ein 1 Bar-Fight sein

**Wieso?**

Sehr geil für Events damit man nochmal eine Chance hat wenn man z.B. Craftkilled wird oder generell früh ausscheidet

**Comment by HitzlikeaBanana** [comment]
Würde die Zeit wann man nicht mehr im Gulag respawnen gar nicht von Spieleranzahlen abhängig machen. (Bis min. 15 als Standard würde ich fühlen) Aber kann man ja mit der Zeit schauen welche Zeit die Leute feiern.

Würde das EQ wenn man im Gulag gewinnt anpassen, damit man das ganze nicht abusen kann z.b sich sofort selbst killen darauf gambeln das man gegen den Kampf gewinnt und dann 32er rc bekommt oder so wäre ja etwas unfair)
Unter min. 5 gestorben = Stone Sword, Compass und Fullinv
Unter min. 10 gestorben =  Stone Sword, Compass und Fullinv + 16er rc
Unter min. 15 gestorben =  Stone Sword, Compass und Fullinv + 32er rc
