### ISSUE TITLE
SpeedHG als schnelle HG Variante

### ISSUE THREAD

**Issue by copyandexecute** [HGLabor/HardcoreGames#62]
### **Was?**

Eine schnelle Variante von HG

### **Details**
**Invincibility**
- Pilze kommen beim Abbauen **direkt** ins Inventar
- Erhöhter Movementspeed
- Man fliegt am Start der Runde über die Map mit Elytra Glideeffekt
- Holz / Toolprozess sollte durch (z.B. Haste) beschleunigt werden

**Ingame**
- Border ist deutlich kleiner (125x125,250x250 **austesten!**)
- Pro Kill / vergangene Minute schrumpft die Border
- Nach einem Kill wird geschaut, ob man verglichen mit anderen Spielern weniger Soups/Recraft hat, falls dies der Fall sein sollte, bekommt man so viele Soups wie es aktuell der **Durchschnitt** oder **Median** ist. Dadurch wird weiteres Farmen verhindert und das Kämpfen kann weitergehen
- Kills sollten noch anderweitig belohnt werden damit man auch Kämpfen **will**
- Teams verboten
- Kits könnten vielleicht alle einen geringen Cooldown haben (muss nicht)

### **Wieso?**

Könnte funny sein als kleine Alternative, wenn man keine Lust hat auf das lange **warten/farmen** hat

**Comment by Wxmble** [comment]
Ja, QHG (QuickHG) hab ich mir auch schon mal gedacht, vielleicht OHNE Mobility-Kits, eigentlich nur mit Combat-Kits. Vielleicht auch eine maximale Anzahl an Spielern (20 oder so) und man startet vielleicht schon mit einem Steinschwert. Den Worldgenerator so ändern dass es ziemlich viele Pilze und gar kein Eisen gibt, sowie ein deutlich generftes Feast (statt Dia-Stuff Iron Stuff)

**Comment by Maquzowastaken** [comment]
Soll das dann eine Setting sein oder ein eigener Modus?
Aber die Idee ist nice

**Comment by Wxmble** [comment]
Eigentlich komplett eigenständiger Modus nehm ich an. Hab aber so meine Bedenken ob dann HG überhaupt noch gespielt wird.

**Comment by Maquzowastaken** [comment]
Nur spieler mit Griefer rang können QHG spielen.
Könnte man ja auch mit dem Namemc Lieblingsserver verbinden

**Comment by copyandexecute** [comment]
> Eigentlich komplett eigenständiger Modus nehm ich an. Hab aber so meine Bedenken ob dann HG überhaupt noch gespielt wird.

Was ja nichts negatives sein muss. Wenn man geile Aspekte von HG und anderen Modi kombinieren kann, wieso nicht

**Comment by copyandexecute** [comment]
> Soll das dann eine Setting sein oder ein eigener Modus?
> 
> Aber die Idee ist nice

Setting

**Comment by Wxmble** [comment]
Und wie könnte man sowas dann spielen?
