### ISSUE TITLE
Zickzack Combo in Schutzzeit

### ISSUE THREAD

**Issue by mooziii** [HGLabor/HardcoreGames#8]
Hits in der Schutzzeit werden zu einer Zickzack combo gezählt

**Comment by copyandexecute** [comment]
Ah gut zu wissen dafür gibt es das attribute isUsable -> man kann in der config einstellen welche kits aktivierbar sind und welche nicht

![grafik](https://user-images.githubusercontent.com/58366920/108602331-b5165280-73a1-11eb-8ec5-10bd17bafa66.png)
